/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbengkel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static javafx.beans.binding.Bindings.or;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Win 7
 */
public class TransaksiBengkel extends javax.swing.JDialog {
    Koneksi objKoneksi;
    private String kd_sp;
    DefaultTableModel table;
    public TransaksiBengkel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        objKoneksi = new Koneksi();
        /*Disable();*/
        inisialisasi();
        autoNumber();
        /*tampilNamaSpareParts();*/
        kd_sp =" ";
        
        ButtonGroup group = new ButtonGroup();
        group.add(rb5);
        group.add(rb10);
        group.add(rb15);  
    }

    TransaksiBengkel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane3 = new javax.swing.JDesktopPane();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        diskon = new javax.swing.JLabel();
        rb5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rb10 = new javax.swing.JRadioButton();
        rb15 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaksi ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane3.setBackground(new java.awt.Color(51, 153, 255));

        jButton6.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton6.setText("Cari");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hapus.png"))); // NOI18N
        jButton3.setText("Hapus");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oli Mesin Shell Advance AX7", "Oli Cooler ", "Busi", "Kampas Rem Depan ", "Kampas Rem Belakang", "Minyak Rem", "Ban Tubelles Zeneos", " ", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jButton5.setText("Buat Baru");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        diskon.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        diskon.setText("Diskon");

        rb5.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        rb5.setText("5%");
        rb5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rb5FocusGained(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Euphemia", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BENGKEL MOTOR");

        jLabel3.setFont(new java.awt.Font("Euphemia", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PULSARIAN");

        jLabel4.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel4.setText("No.Service");

        jLabel5.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel5.setText("Sparepart");

        jLabel6.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel6.setText("Harga");

        jLabel7.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel7.setText("Jumlah Item");

        jButton1.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/simpan.png"))); // NOI18N
        jButton1.setText("Simpan");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rb10.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        rb10.setText("10%");
        rb10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rb10FocusGained(evt);
            }
        });

        rb15.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        rb15.setText("15%");
        rb15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rb15FocusGained(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logout.png"))); // NOI18N
        jButton4.setText("Keluar");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(19, 19, 19)
                                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(jTextField3)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                                .addComponent(rb5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rb10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rb15))
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(diskon))
                                .addGap(38, 38, 38)
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jDesktopPane3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5});

        jDesktopPane3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField3, jTextField4});

        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jButton6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diskon)
                    .addComponent(rb5)
                    .addComponent(rb10)
                    .addComponent(rb15))
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane3.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(diskon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(rb5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(rb10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(rb15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabel1(){
        table = new DefaultTableModel();
        jTable1.setModel(table);
        table.addColumn("No Service");
        table.addColumn("Kode Sparepart");
        table.addColumn("Harga");
        table.addColumn("Jumlah Item");
        table.addColumn("Discount");
        table.addColumn("Jumlah Bayar");
    }
    
    private void tampil(){
        try{
         Connection con = objKoneksi.bukaKoneksi();
         Statement st = con.createStatement();
         String sql = "SELECT * FROM isi";
         ResultSet rs = st.executeQuery(sql);
         while(rs.next()){
             Object[] o;
             o = new Object[6];
             o[0] = rs.getString("no_service");
             o[1] = rs.getString("kd_sp");
             o[2] = rs.getString("harga");
             o[3] = rs.getString("jml_item");
             o[4] = rs.getString("discount");
             o[5] = rs.getString("jml_bayar");
             table.addRow(o);
         }
         con.close();
         st.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:  
    TambahData();
    tabel1();
    tampil();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        CariData(); 
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        detailSpareParts();
        //CariData();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       // TODO add your handling code here:
        inisialisasi();
        bersih();
        autoNumber();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    private void rb15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rb15FocusGained
     inisialisasi2(); /* Enabled();*/
    }//GEN-LAST:event_rb15FocusGained

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void rb10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rb10FocusGained
        inisialisasi2();// TODO add your handling code here:
        /*Enabled();*/
    }//GEN-LAST:event_rb10FocusGained

    private void rb5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rb5FocusGained
       inisialisasi2(); // TODO add your handling code here:
        /*Enabled();*/
    }//GEN-LAST:event_rb5FocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CariData();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()== jButton4){
           int pilih = JOptionPane.showConfirmDialog(null, "Yakin Mau LOGOUT?","Logout",JOptionPane.YES_NO_CANCEL_OPTION);
           if(pilih == JOptionPane.YES_OPTION){
            Menu_Utama menu = new Menu_Utama();
            menu.show();
            this.dispose();
        
           } 
           
        }
     

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hapusData();
        tabel1();
        tampil();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UbahData();
        tabel1();
        tampil();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tabel1();
        tampil();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int discount = 0;
        int jml_bayar = 0;
        
        
        String kode = "SELECT * FROM isi WHERE no_service = '"
                +jTextField1.getText()+"'";
        String sql = "INSERT INTO isi VALUES('"+jTextField1.getText()+"','"
                 + kd_sp +"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"
                 +discount+"','"+jml_bayar+"')";
        try{
         Connection con = objKoneksi.bukaKoneksi();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery(kode);
         if(rs.next()){
             JOptionPane.showMessageDialog(this,"No Service Sudah Ada","Peringatan",JOptionPane.WARNING_MESSAGE);
             jTextField3.setText("");
             jTextField4.setText("");
             rb5.setSelected(true);
         }
         else{
             st.executeUpdate(sql);
             JOptionPane.showMessageDialog(null,"Data Berhasil DiTambahkan","Data Masuk",JOptionPane.INFORMATION_MESSAGE);
             bersih();
             tabel1();
             tampil();
             con.close();
         }
        }catch(SQLException e){
        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1MouseClicked
    private void detailSpareParts(){
       // String nama_barang;
        try{
        Connection con = objKoneksi.bukaKoneksi();
        Statement st = con.createStatement();
        String sql = "SELECT * FROM sparepart WHERE nama_barang = '"+jComboBox1.getSelectedItem()+"'";
        ResultSet rs = st.executeQuery(sql);
        if(rs.next())
        {
        jTextField3.setText(rs.getString("harga"));
       /* Disable();*/
        kd_sp = rs.getString("kd_sp");
        }
        con.close();
        st.close();
        System.out.println(""+kd_sp);
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    private void Disable(){
      /*  jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false); */       
    }
    private void Enabled(){/*
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    jButton3.setEnabled(true);*/    
    }
    private void autoNumber(){
    String noService = "SER000";
    int i= 0;
        try{
              Connection con = objKoneksi.bukaKoneksi();
              Statement st = con.createStatement();
              String sql ="SELECT no_service FROM isi";
              ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    noService = rs.getString("no_service");
                   }
       
        noService = noService.substring(3);
        i = Integer.parseInt(noService)+1;
        noService = "00"+1;
        noService = "SER"+noService.substring(noService.length()-3);
        jTextField1.setText(noService);
        }catch(SQLException e){
        System.out.println(e.getMessage());
}
    }
    private void inisialisasi(){
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false); 
    }
    private void inisialisasi2(){
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    jButton3.setEnabled(true); 
    }  
    private void TambahData(){
       
        int discount = 0;
        int jml_bayar = 0;
        
        if(rb5.isSelected()){
            discount = 5;
        }
        if(rb10.isSelected()){
            discount = 10;
        }
        if(rb15.isSelected()){
            discount = 15;
        }
        
        jml_bayar = Integer.parseInt(jTextField3.getText()) * Integer.parseInt(jTextField4.getText());
        jml_bayar = jml_bayar -(jml_bayar * discount/100);
     try{
         Connection con = objKoneksi.bukaKoneksi();
         Statement st = con.createStatement();
         String kode = "SELECT * FROM isi WHERE no_service = '"+jTextField1.getText()+"'";
         String sql = "INSERT INTO isi VALUES('"+jTextField1.getText()+"','"
                 + kd_sp +"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"
                 +discount+"','"+jml_bayar+"')";
         int sukses = st.executeUpdate(sql);
            if(sukses > 0){
                JOptionPane.showMessageDialog(rootPane,"Data Berhasil Di Tambahkan");
                
            }
            else{
                 JOptionPane.showMessageDialog(rootPane,"Data Tidak Berhasil ditambahkan");
            }
      con.close();
      st.close();
     }catch(SQLException e){
         System.out.println(e.getMessage());
     }
      }
    
    private void CariData(){
        try{
            Connection con = objKoneksi.bukaKoneksi();
            Statement st = con.createStatement();
            String sql = "SELECT * FROM isi WHERE no_service = '"+jTextField1.getText()
                    +"'";// + " and kd_sp = '"+kd_sp+"'";
        ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                jTextField4.setText(rs.getString("jml_item"));
                //kd_sp = rs.getString("kd_sp");
                if(rs.getString("discount").equals("5")) {
                    if(rs.getString("kd_sp").equals("1")){
                        jComboBox1.setSelectedIndex(0);
                    }
                    if(rs.getString("kd_sp").equals("2")){
                        jComboBox1.setSelectedIndex(1);
                    }
                    if(rs.getString("kd_sp").equals("3")){
                        jComboBox1.setSelectedIndex(2);
                    }
                    if(rs.getString("kd_sp").equals("4")){
                        jComboBox1.setSelectedIndex(3);
                    }
                    if(rs.getString("kd_sp").equals("5")){
                        jComboBox1.setSelectedIndex(4);
                    }
                    if(rs.getString("kd_sp").equals("6")){
                        jComboBox1.setSelectedIndex(5);
                    }
                    if(rs.getString("kd_sp").equals("7")){
                        jComboBox1.setSelectedIndex(6);
                    }
                    rb5.setSelected(true);
                }
                if(rs.getString("discount").equals("10")){
                    if(rs.getString("kd_sp").equals("1")){
                        jComboBox1.setSelectedIndex(0);
                    }
                    if(rs.getString("kd_sp").equals("2")){
                        jComboBox1.setSelectedIndex(1);
                    }
                    if(rs.getString("kd_sp").equals("3")){
                        jComboBox1.setSelectedIndex(2);
                    }
                    if(rs.getString("kd_sp").equals("4")){
                        jComboBox1.setSelectedIndex(3);
                    }
                    if(rs.getString("kd_sp").equals("5")){
                        jComboBox1.setSelectedIndex(4);
                    }
                    if(rs.getString("kd_sp").equals("6")){
                        jComboBox1.setSelectedIndex(5);
                    }
                    if(rs.getString("kd_sp").equals("7")){
                        jComboBox1.setSelectedIndex(6);
                    }
                    rb10.setSelected(true);
                }
                if(rs.getString("discount").equals("15")){
                    if(rs.getString("kd_sp").equals("1")){
                        jComboBox1.setSelectedIndex(0);
                    }
                    if(rs.getString("kd_sp").equals("2")){
                        jComboBox1.setSelectedIndex(1);
                    }
                    if(rs.getString("kd_sp").equals("3")){
                        jComboBox1.setSelectedIndex(2);
                    }
                    if(rs.getString("kd_sp").equals("4")){
                        jComboBox1.setSelectedIndex(3);
                    }
                    if(rs.getString("kd_sp").equals("5")){
                        jComboBox1.setSelectedIndex(4);
                    }
                    if(rs.getString("kd_sp").equals("6")){
                        jComboBox1.setSelectedIndex(5);
                    }
                    if(rs.getString("kd_sp").equals("7")){
                        jComboBox1.setSelectedIndex(6);
                    }
                    rb15.setSelected(true);
                }
                
                inisialisasi();
                jButton2.setEnabled(true);
                jButton3.setEnabled(true);
            } else{
            JOptionPane.showMessageDialog(rootPane,"Data Tidak ada");
            inisialisasi();
            jButton1.setEnabled(true);
            jTextField4.setText("");
            rb5.setSelected(true);
            }
        con.close();
        st.close();
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    private void UbahData(){
        int discount = 0;
        int jml_bayar = 0;
        
        if(rb5.isSelected()){
            discount = 5;
        }
        if(rb10.isSelected()){
            discount = 10;
        }
        if(rb15.isSelected()){
            discount = 15;
        }
        
        jml_bayar = Integer.parseInt(jTextField3.getText()) * Integer.parseInt(jTextField4.getText());
        jml_bayar = jml_bayar - (jml_bayar * discount / 100);
        
        try{
        Connection con = objKoneksi.bukaKoneksi();
        Statement st = con.createStatement();
        String sql = "UPDATE isi SET jml_item = '"+jTextField4.getText()+"', discount = '"+discount+"', jml_bayar = '"+jml_bayar+"' WHERE no_service = '"+jTextField1.getText()+"' and kd_sp = '"+kd_sp+"'"; 
        int sukses = st.executeUpdate(sql);
        if(sukses > 0 ){
            JOptionPane.showMessageDialog(null,"Data Berhasil di Edit","Update",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Data Tidak Berhasil di Edit");
        }
       con.close();
       st.close();
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
    }
    private void bersih(){
        jTextField4.setText("");
        jTextField3.setText("");
        rb5.setSelected(true);
    }
    private void hapusData(){
    int pilih = JOptionPane.showConfirmDialog(this, "Anda Yakin Untuk Menghapus Data ?","Hapus Data",JOptionPane.OK_CANCEL_OPTION);
    if(pilih == JOptionPane.OK_OPTION){
    String sql = "DELETE FROM isi WHERE no_service = '"+jTextField1.getText()+"' AND kd_sp = '"+kd_sp+" '";
       
    try{
            Connection con = objKoneksi.bukaKoneksi();
            Statement st = con.createStatement();      
            int sukses = st.executeUpdate(sql);
            if(sukses > 0){
                JOptionPane.showMessageDialog(rootPane,"Data Berhasil Di Hapus");
                bersih();
                inisialisasi();
            }else{
                JOptionPane.showMessageDialog(rootPane,"Data Tidak Berhasil Di Hapus");
            }
           con.close();
           st.close();
        } catch(SQLException e){
            System.out.println(e.getMessage());
            }
    }
 }   
  
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiBengkel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiBengkel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiBengkel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiBengkel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TransaksiBengkel dialog = new TransaksiBengkel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diskon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb15;
    private javax.swing.JRadioButton rb5;
    // End of variables declaration//GEN-END:variables

    private void detailSparepart() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
